import net.ltgt.gradle.errorprone.CheckSeverity

plugins {
    id "maven-publish"
    id "idea"
    id "net.neoforged.moddev.legacyforge" version "${mdg_version}" apply false
    id "net.ltgt.errorprone" version "5.1.0" apply false
}

def isGITHU_ACTION = System.getenv("GITHUB_ACTION")
def gitHash() {
    String hash = System.getenv("GITHUB_SHA")
    if (hash != null) return hash.substring(0,8)
    return ""
}

subprojects {
    apply plugin: "maven-publish"
    apply plugin: "java"
    apply plugin: "idea"
    apply plugin: "net.ltgt.errorprone"
    group = rootProject.maven_group
    version = "${project.mod_version}-${rootProject.minecraft_version}"
    java.toolchain.languageVersion = JavaLanguageVersion.of(17)
    apply from: 'https://raw.githubusercontent.com/GT-Reimagined/GradleScripts/main/repositories.gradle'

    java {
        withSourcesJar()
    }

    dependencies {
        implementation("org.jspecify:jspecify:1.0.0")
        errorprone "com.uber.nullaway:nullaway:0.13.8"
        errorprone "com.google.errorprone:error_prone_core:2.42.0"
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        options.errorprone {
            check("NullAway", CheckSeverity.ERROR)
            check("AlmostJavadoc", CheckSeverity.OFF)
            option("NullAway:AnnotatedPackages", "org.gtreimagined.tesseract.graph")
        }
        // Include to disable NullAway on test code
        if (name.toLowerCase().contains("test")) {
            options.errorprone {
                disable("NullAway")
            }
        }
    }

    if (isGITHU_ACTION) {
        version = version + "-" + gitHash()
        println("In CI mode")
    }
}