plugins {
    id "net.neoforged.moddev.legacyforge"
}
archivesBaseName = "${project.tesseract_archive_base_name}-common"

legacyForge {
    mcpVersion = "${project.minecraft_version}"
    parchment {
        minecraftVersion = project.minecraft_version
        mappingsVersion = project.mappings_version
    }
}

publishing {
    publications {
        mavenJava(org.gradle.api.publish.maven.MavenPublication) {
            from components.java
        }
    }

    repositories {
        def isCI = System.getenv("CI")
        if (isCI) {
            maven {
                url System.getenv("local_maven_url")
            }
        } else {
            mavenLocal()
        }
    }
}
